
//Create
export const CREATE_ASK = 'CREATE_ASK'
export const CREATE_ASK_PENDING = `${CREATE_ASK}_PENDING`
export const CREATE_ASK_FULFILLED = `${CREATE_ASK}_FULFILLED`
export const CREATE_ASK_REJECTED = `${CREATE_ASK}_REJECTED`


//Create
export const LIST_ASK = 'LIST_ASK'
export const LIST_ASK_PENDING = `${LIST_ASK}_PENDING`
export const LIST_ASK_FULFILLED = `${LIST_ASK}_FULFILLED`
export const LIST_ASK_REJECTED = `${LIST_ASK}_REJECTED`