
//Auth manuel user
export const AUTH = 'AUTH'
export const AUTH_PENDING = `${AUTH}_PENDING`
export const AUTH_FULFILLED = `${AUTH}_FULFILLED`
export const AUTH_REJECTED = `${AUTH}_REJECTED`

// Auth facebook
// export const AUTH_FACEBOOK = 'AUTH_FACEBOOK'
// export const AUTH_FACEBOOK_PENDING = `${AUTH_FACEBOOK}_PENDING`
// export const AUTH_FACEBOOK_FULFILLED = `${AUTH_FACEBOOK}_FULFILLED`
// export const AUTH_FACEBOOK_REJECTED = `${AUTH_FACEBOOK}_REJECTED`


// Auth requested
export const AUTH_REQUESTED = 'AUTH_REQUESTED'


// Auth logout
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
 

//Sign Up User - register
export const AUTH_SIGNUP_USER = 'AUTH_SIGNUP_USER'
export const AUTH_SIGNUP_USER_PENDING = `${AUTH_SIGNUP_USER}_PENDING`
export const AUTH_SIGNUP_USER_FULFILLED = `${AUTH_SIGNUP_USER}_FULFILLED`
export const AUTH_SIGNUP_USER_REJECTED = `${AUTH_SIGNUP_USER}_REJECTED`


// check if username or email existe
export const AUTH_USER_NOT_EXISTS = 'AUTH_USER_NOT_EXISTS'
export const AUTH_USER_NOT_EXISTS_PENDING = `${AUTH_USER_NOT_EXISTS}_PENDING`
export const AUTH_USER_NOT_EXISTS_FULFILLED = `${AUTH_USER_NOT_EXISTS}_FULFILLED`
export const AUTH_USER_NOT_EXISTS_REJECTED = `${AUTH_USER_NOT_EXISTS}_REJECTED`


