
// get notification
export const LIST_NOTIFICATION = 'LIST_NOTIFICATION'
export const LIST_NOTIFICATION_PENDING = `${LIST_NOTIFICATION}_PENDING`
export const LIST_NOTIFICATION_FULFILLED = `${LIST_NOTIFICATION}_FULFILLED`
export const LIST_NOTIFICATION_REJECTED = `${LIST_NOTIFICATION}_REJECTED`