
//Get friends facebook
export const LIST_FACEBOOK_FRIEND = 'LIST_FACEBOOK_FRIEND'
export const LIST_FACEBOOK_FRIEND_PENDING = `${LIST_FACEBOOK_FRIEND}_PENDING`
export const LIST_FACEBOOK_FRIEND_FULFILLED = `${LIST_FACEBOOK_FRIEND}_FULFILLED`
export const LIST_FACEBOOK_FRIEND_REJECTED = `${LIST_FACEBOOK_FRIEND}_REJECTED`


// post follow user
export const FOLLOW_USER = 'FOLLOW_USER'
export const FOLLOW_USER_PENDING = `${FOLLOW_USER}_PENDING`
export const FOLLOW_USER_FULFILLED = `${FOLLOW_USER}_FULFILLED`
export const FOLLOW_USER_REJECTED = `${FOLLOW_USER}_REJECTED`


// post invite all
export const FOLLOW_ALL_USER = 'FOLLOW_ALL_USER'
export const FOLLOW_ALL_USER_PENDING = `${FOLLOW_ALL_USER}_PENDING`
export const FOLLOW_ALL_USER_FULFILLED = `${FOLLOW_ALL_USER}_FULFILLED`
export const FOLLOW_ALL_USER_REJECTED = `${FOLLOW_ALL_USER}_REJECTED`


// refresh state after follow facebook friend
export const FOLLOW_FACEBOOK_FRIEND = 'FOLLOW_FACEBOOK_FRIEND'


// create facebook list (when user not fb login)
export const CREATE_FACEBOOK_FRIEND = 'CREATE_FACEBOOK_FRIEND'
export const CREATE_FACEBOOK_FRIEND_PENDING = `${CREATE_FACEBOOK_FRIEND}_PENDING`
export const CREATE_FACEBOOK_FRIEND_FULFILLED = `${CREATE_FACEBOOK_FRIEND}_FULFILLED`
export const CREATE_FACEBOOK_FRIEND_REJECTED = `${CREATE_FACEBOOK_FRIEND}_REJECTED`


