
//get top spitcher
export const LIST_TOP_SPITCHER = 'LIST_TOP_SPITCHER'
export const LIST_TOP_SPITCHER_PENDING = `${LIST_TOP_SPITCHER}_PENDING`
export const LIST_TOP_SPITCHER_FULFILLED = `${LIST_TOP_SPITCHER}_FULFILLED`
export const LIST_TOP_SPITCHER_REJECTED = `${LIST_TOP_SPITCHER}_REJECTED`

//get top tag
export const LIST_TOP_TAG = 'LIST_TOP_TAG'
export const LIST_TOP_TAG_PENDING = `${LIST_TOP_TAG}_PENDING`
export const LIST_TOP_TAG_FULFILLED = `${LIST_TOP_TAG}_FULFILLED`
export const LIST_TOP_TAG_REJECTED = `${LIST_TOP_TAG}_REJECTED`
