
//Update user
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_PENDING = `${UPDATE_USER}_PENDING`
export const UPDATE_USER_FULFILLED = `${UPDATE_USER}_FULFILLED`
export const UPDATE_USER_REJECTED = `${UPDATE_USER}_REJECTED`

//get info user from token
export const USER_FROM_TOKEN = 'USER_FROM_TOKEN'

// get current user profile
export const RETREIVE_USER = 'RETREIVE_USER'
export const RETREIVE_USER_PENDING = `${RETREIVE_USER}_PENDING`
export const RETREIVE_USER_FULFILLED = `${RETREIVE_USER}_FULFILLED`
export const RETREIVE_USER_REJECTED = `${RETREIVE_USER}_REJECTED`

// get other user profile
export const VISIT_USER = 'VISIT_USER'
export const VISIT_USER_PENDING = `${VISIT_USER}_PENDING`
export const VISIT_USER_FULFILLED = `${VISIT_USER}_FULFILLED`
export const VISIT_USER_REJECTED = `${VISIT_USER}_REJECTED`