# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'

target 'spitchtv' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for spitchtv
  pod 'Firebase'
  #pod 'Firebase/Messaging'
  pod 'Firebase/Messaging', '3.17.0'
  pod 'QBImagePickerController'
  pod 'RSKImageCropper'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'spitchtvTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
