export const INIT_NEW_SPITH = 'INIT_NEW_SPITH'
export const ADD_CLIP_NEW_SPITCH = 'ADD_CLIP_NEW_SPITCH'
export const REMOVE_CLIP_NEW_SPITCH = 'REMOVE_CLIP_NEW_SPITCH'
export const MERGE_CLIP_NEW_SPITCH = 'MERGE_CLIP_NEW_SPITCH'
export const RESET_NEW_SPITCH = 'RESET_NEW_SPITCH'

export const UPLOAD_SPITCH = 'UPLOAD_SPITCH'
export const UPLOAD_SPITCH_PENDING = `${UPLOAD_SPITCH}_PENDING`
export const UPLOAD_SPITCH_FULFILLED = `${UPLOAD_SPITCH}_FULFILLED`
export const UPLOAD_SPITCH_REJECTED = `${UPLOAD_SPITCH}_REJECTED` 

export const LIKE_SPITCH = 'LIKE_SPITCH'
export const LIKE_SPITCH_PENDING = `${LIKE_SPITCH}_PENDING`
export const LIKE_SPITCH_FULFILLED = `${LIKE_SPITCH}_FULFILLED`
export const LIKE_SPITCH_REJECTED = `${LIKE_SPITCH}_REJECTED` 

export const RETRIEVE_SPITCH = 'RETRIEVE_SPITCH'
export const RETRIEVE_SPITCH_PENDING = `${RETRIEVE_SPITCH}_PENDING`
export const RETRIEVE_SPITCH_FULFILLED = `${RETRIEVE_SPITCH}_FULFILLED`
export const RETRIEVE_SPITCH_REJECTED = `${RETRIEVE_SPITCH}_REJECTED` 